services:
  - type: web
    name: musichub-pytubefix-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PORT
        value: 5000
