services:
  - type: web
    name: musichub-pytubefix
    runtime: python
    rootDir: python-api
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
    plan: free
