services:
  - type: web
    name: musichub-pytubefix
    runtime: python
    rootDir: python-api
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
